POST http://localhost:3001/api/patients
content-type: application/json

{
    "name": "Oheneba1",
    "dateOfBirth": "1985-07-22",
    "ssn": "123456-abc4",
    "gender": "Male",
    "occupation": "consumer"
}